// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/settings-refined/Elevated.tsx": () => import("../components/mockups/settings-refined/Elevated.tsx"),
  "./components/mockups/settings-refined/Sharper.tsx": () => import("../components/mockups/settings-refined/Sharper.tsx"),
  "./components/mockups/settings-vibes/EnergeticManga.tsx": () => import("../components/mockups/settings-vibes/EnergeticManga.tsx"),
  "./components/mockups/settings-vibes/MinimalFormal.tsx": () => import("../components/mockups/settings-vibes/MinimalFormal.tsx"),
  "./components/mockups/settings-vibes/WarmEditorial.tsx": () => import("../components/mockups/settings-vibes/WarmEditorial.tsx")
};
